
stages:          # List of stages for jobs, and their order of execution
  - install
  - test

build-job:       # This job runs in the build stage, which runs first.
  stage: install
  script:
    - echo "安装依赖"
    - npm install -D
    - cd ./test/smoke/template
    - npm install -D
  allow_failure: true

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "开始测试"
    - npm test
